/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-11-03 06:53:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Member.Seok;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1572075545569L));
    _jspx_dependants.put("jar:file:/C:/Users/KOSMO-08/Desktop/ProjectJSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/KOSMO-08/Desktop/ProjectJSP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <!-- jstl을 사용하기 위한 디렉티브 -->\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(' ');
      out.write('\r');
      out.write('\n');

    request.setCharacterEncoding("UTF-8"); //요청 받아온 글자 깨지지 안도록 UTF-8설정

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/init.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../css/common.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/jquery-2.1.1.min.js\"> </script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/prefixfree.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/common.js\"></script>\r\n");
      out.write("    <!--개인 css, js-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/login.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>Login Page</title>\r\n");
      out.write("    <script>\r\n");
      out.write("    /* 로그인 유효성 검사  */\r\n");
      out.write("    \tfunction login_validate(){\r\n");
      out.write("    \t\tvar frmLogin = document.frmLogin;\r\n");
      out.write("    \t\tvar user_id = frmLogin.user_id.value;\r\n");
      out.write("    \t\tvar user_pw = frmLogin.user_pw.value;\r\n");
      out.write("    \t\t//var idRegExp = /^[a-z0-9]{4,20}$/;\r\n");
      out.write("\r\n");
      out.write("    \t\t//if(frmLogin.user_id.value==idRegExp){\r\n");
      out.write("    \t\t//\talert(\"아이디는 영문자와 숫자 5~20자리로 입력해야합니다.\");\r\n");
      out.write("    \t\t//\tfrmLogin.user_id.value = \"\";\r\n");
      out.write("    \t\t//\tfrmLogin.user_id.focus();\r\n");
      out.write("    \t\t//}\r\n");
      out.write("    \t\tif((user_id.length==0||user_id==\"\")||\r\n");
      out.write("    \t\t\t\t(user_pw.length==0||user_pw==\"\")){\r\n");
      out.write("    \t\t\talert(\"ID와 PassWord는 필수입니다. \");\r\n");
      out.write("    \t\t\tfrmLogin.user_id.focus();\r\n");
      out.write("    \t\t}else if(user_id.length<=4||user_id.length>=21){\r\n");
      out.write("    \t\t\talert(\"아이디는 5글자이상 20글자 이하만 입력가능합니다.\");    \t\t\t\r\n");
      out.write("    \t\t\tfrmLogin.user_id.focus();\r\n");
      out.write("    \t\t}else if(user_pw.length<=7||user_pw.length>=17){\r\n");
      out.write("    \t\t\talert(\"비밀번호는 8글자이상 16글자 이하만 입력가능합니다.\");\r\n");
      out.write("    \t\t\tfrmLogin.user_pw.focus();\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t//else if(user_id){\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t//\tfrmLogin.user_id.value.replace(/\\s/gi, \"\");\r\n");
      out.write("    \t\t//\tuser_id.replace(/(^\\s*)|(\\s*$)/, '');\r\n");
      out.write("    \t\t//}\r\n");
      out.write("    \t\t//else if(document.frm.memberCheck.value!=true){\r\n");
      out.write("\t   \t\t//\talert(\"회원정보가 없습니다.\");    \t\t\t\r\n");
      out.write("    \t\t//}\r\n");
      out.write("    \t\telse{    \r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t\tfrmLogin.method=\"post\";\r\n");
      out.write("    \t\t\tfrmLogin.action=\"../../../project/login/loginCheck.do\";\r\n");
      out.write("    \t\t\tfrmLogin.submit();\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    /* 페이지 이동  */\r\n");
      out.write("        function member(){\r\n");
      out.write("            window.location.href=\"Member/An/postRead.html\";\r\n");
      out.write("        };\r\n");
      out.write("        function id(){\r\n");
      out.write("            window.location.href=\"find_id.jsp\";\r\n");
      out.write("        };\r\n");
      out.write("        function password(){\r\n");
      out.write("            window.location.href=\"find_pwd.jsp\";\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--main_header_wrap-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!--//main_header_wrap-->\r\n");
      out.write("    <!--section-->\r\n");
      out.write("    <section>\r\n");
      out.write("    <div id=\"PPS\" class=\"content\">\r\n");
      out.write("    <!--Login-->\r\n");
      out.write("    <form name=\"frmLogin\" method=\"post\"  encType=\"UTF-8\">\r\n");
      out.write("    <div class=\"loginWrap\">\r\n");
      out.write("    <div>\r\n");
      out.write("        <a href=\"javascript:window.location.reload();\"><img src=\"http://placehold.it/500x160\" title=\"mainPic\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <input class=\"login_id\" placeholder=\"   아이디\" maxlength=\"20\"\r\n");
      out.write("    type=\"text\" required=\"required\" name=\"user_id\"><br>\r\n");
      out.write("    <input class=\"login_pwd\" placeholder=\"   비밀번호\" maxlength=\"17\" \r\n");
      out.write("    type=\"password\" required=\"required\" name=\"user_pw\">\r\n");
      out.write("    <hr class=\"loginhr\">\r\n");
      out.write("    <p class=\"btn_login\">\r\n");
      out.write("        <a  href=\"javascript:login_validate();\">로그인</a>        \r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"buttonwrap\">\r\n");
      out.write("        <div class=\"memberbutton\"><a href=\"javascript:member();\" ><img src=\"./images/login_b_12.gif\" title=\"회원가입\"></a></div>\r\n");
      out.write("        <div class=\"idsearch\"><a href=\"javascript:id();\"><img src=\"./images/login_b_15.gif\" title=\"id 찾기\"></a></div>\r\n");
      out.write("        <div class=\"pwdsearch\"><a href=\"javascript:password();\"><img src=\"./images/login_b_17.gif\" title=\"비밀번호 찾기\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <!--//Login-->\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!--//section-->\r\n");
      out.write("<!--main_footer-->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!--//main_footer-->    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /Member/Seok/login_main.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /Member/Seok/login_main.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/Member/Seok/login_main.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
